//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by mudclient.rc
//
#define IDR_MAINFRAME                   128
#define IDS_RESET_COLORS_CONFIRM        129
#define IDS_NETWORK_FAILED              130
#define IDS_RESET_OSC_CONFIRM           130
#define IDS_NEW_PROFILE                 131
#define IDS_NEW_WORLD                   132
#define IDS_ERROR_INIT_NETWORK          200
#define IDS_ERROR_NEWPROFILE_FAILED     201
#define IDD_PROPERTY_ALIASES            202
#define IDS_ERROR_COPYPROFILE_FAILED    202
#define IDD_PROPERTY_TWOPARAMS          202
#define IDS_ERROR_INITPROFILES_FAILED   203
#define IDD_PROPERTY_BASE               204
#define IDS_ERROR_SAVEPROFILE_FAILED    204
#define IDD_PROPERTY_HOTKEYS            205
#define IDS_ERROR_CURRENTSAVEPROFILE_FAILED 205
#define IDD_PROPERTY_HIGHLIGHTS         206
#define IDS_ERROR_SCRIPTENGINE_FAILED   206
#define IDD_PROPERTY_COLORS_FONT        207
#define IDS_ERROR_MODULES               207
#define IDD_LOAD_PROFILE                208
#define IDS_ERROR_LOADPROFILE_FAILED    208
#define IDD_NEW_PROFILE                 209
#define IDS_ERROR_LASTLOAD_FAILED       209
#define IDD_PROPERTY_COMMON             210
#define IDD_PROPERTY_GROUPS             211
#define IDD_PROPERTY_ONEPARAM           212
#define IDD_PROPERTY_TABWORDS           213
#define IDD_PROPERTY_TIMERS             214
#define IDD_PLUGINS                     215
#define IDD_NEW_WORLD                   218
#define IDD_WELCOME                     219
#define IDR_BINARY_WELCOME              220
#define IDD_PASSWORD                    221
#define IDD_STARTUP_WORLD               222
#define IDD_FIND                        223
#define IDD_MODE                        224
#define IDD_PROPERTY_VARS               225
#define IDC_BUTTON_PROP_COLORS          1000
#define IDC_BUTTON_PROP_ALIASES         1001
#define IDC_BUTTON_PROP_ACTIONS         1002
#define IDC_BUTTON_PROP_HIGHLIGHTS      1003
#define IDC_BUTTON_PROP_HOTKEYS         1004
#define IDC_BUTTON_PROPS_SUBS           1005
#define IDC_BUTTON_PROP_COMMON          1006
#define IDC_BUTTON_PROP_GROUPS          1007
#define IDC_BUTTON_PROPS_GAGS           1008
#define IDC_BUTTON_PROPS_ANTISUBS       1009
#define IDC_STATIC_BLLINE               1010
#define IDC_BUTTON_PROP_TABWORDS        1011
#define IDC_BUTTON_PROP_TIMERS          1012
#define IDC_BUTTON_ADD                  1013
#define IDC_BUTTON_PROP_VARS            1013
#define IDC_BUTTON_DEL                  1014
#define IDC_STATIC_BL1                  1015
#define IDC_STATIC_BL2                  1016
#define IDC_EDIT_ALIAS                  1017
#define IDC_BUTTON_RESET                1020
#define IDC_BUTTON_RENAME               1021
#define IDC_EDIT_PATTERN                1022
#define IDC_EDIT_ALIAS_TEXT             1023
#define IDC_EDIT_VARNAME                1023
#define IDC_EDIT_VARVALUE               1023
#define IDC_EDIT_PATTERN_TEXT           1024
#define IDC_LIST                        1025
#define IDC_EDIT_HOTKEY                 1026
#define IDC_EDIT_HOTKEY_TEXT            1027
#define IDC_EDIT_HIGHLIGHT_TEXT         1040
#define IDC_STATIC_COLORS_WINDOW        1045
#define IDC_BUTTON_FONT                 1046
#define IDC_BUTTON_BKGND_COLOR          1047
#define IDC_BUTTON_COLOR_RESET          1048
#define IDC_LIST_PROFILE_GROUP          1049
#define IDC_LIST_PROFILE                1050
#define IDC_LIST_PROFILE_NEW            1051
#define IDC_EDIT_PROFILE_NEW            1052
#define IDC_CHECK_HIGHLIGHTS_UNDERLINE  1060
#define IDC_CHECK_HIGHLIGHTS_FLASH      1061
#define IDC_STATIC_TEXTCOLOR            1063
#define IDC_STATIC_BKGCOLOR             1064
#define IDC_STATIC_HIGHLIGHTS_EXAMPLE   1065
#define IDC_CHECK_HIGHLIGHTS_ITALIC     1066
#define IDC_EDIT_VIEW_HISTORY           1069
#define IDC_EDIT_CMD_HISTORY            1070
#define IDC_BUTTON_UP                   1074
#define IDC_BUTTON_DOWN                 1075
#define IDC_EDIT_GROUP                  1078
#define IDC_CHECK_GROUP_ON              1079
#define IDC_COMBO_GROUP                 1080
#define IDC_CHECK_GROUP_FILTER          1081
#define IDC_COMBO_GROUP2                1081
#define IDC_COMBO_FILTER                1081
#define IDC_STATIC_LABEL2               1082
#define IDC_STATIC_LABEL1               1083
#define IDC_STATIC_TITLE                1084
#define IDC_CHECK_SHOW_SYSTEM_CMDS      1085
#define IDC_CHECK_CLEAR_BAR             1086
#define IDC_EDIT_NUMBER                 1087
#define IDC_CHECK_NEWLINECMD            1087
#define IDC_EDIT_PROMPT_PCRE            1110
#define IDC_CHECK_DISABLE_DOUBLE_YA     1111
#define IDC_CHECK_HISTORYTAB            1113
#define IDC_EDIT_PLUGIN_DESC            1114
#define IDC_BUTTON_ONOFF                1115
#define IDC_BUTTON_PLUGINUP             1116
#define IDC_BUTTON_PLUGINDOWN           1117
#define IDC_CHECK_PLUGINSLOGS           1118
#define IDC_EDIT_PLUGINSLOGS            1119
#define IDC_EDIT_NEWWORLD_NAME          1120
#define IDC_CHECK_DISABLE_OSC           1120
#define IDC_EDIT_NEWWORLD_PROFILE       1121
#define IDC_COMBO_CODEPAGE              1122
#define IDC_COMBO_LOGFORMAT             1123
#define IDC_RADIO_PROMT_GA              1124
#define IDC_RADIO_PROMT_PCRE            1125
#define IDC_CHECK_DONTSHOW              1126
#define IDC_STATIC_RICHBOXPLACE         1129
#define IDC_EDIT_PASSWORD               1130
#define IDC_BUTTON_COLOR_RESETOSC       1131
#define IDC_BUTTON_REPLACE              1132
#define IDC_LIST_STARTUP_WORLD          1133
#define IDC_CHECK_OPEN_ABOUT            1134
#define IDC_CHECK_SOFTSCROLL            1135
#define IDC_EDIT_STARTUP_PROFILE        1136
#define IDC_EDIT_FINDTEXT               1137
#define IDC_EDIT_STARTUP_FOLDER         1138
#define IDC_COMBO_FINDWINDOW            1139
#define IDC_RADIO_END_BEGIN             1140
#define IDC_RADIO_BEGIN_END             1141
#define IDC_CHECK_UNKNOWNCMD            1142
#define IDC_CHECK_ANYFONTS              1143
#define IDC_CHECK_DISABLEALT            1144
#define IDC_CHECK_MOVETOTRAY            1145
#define IDC_LIST_COMPONENTS             1146
#define IDC_CHECK_CREATELINK            1147
#define IDC_CHECK_HIDE_OFFGROUPS        1148
#define ID_SETTINGS                     32776
#define ID_WINDOW_1                     32777
#define ID_WINDOW_2                     32778
#define ID_WINDOW_3                     32779
#define ID_WINDOW_4                     32780
#define ID_WINDOW_5                     32781
#define ID_WINDOW_6                     32782
#define ID_VIEW_FIND                    32783
#define ID_PLUGINS                      32791
#define ID_NEWPROFILE                   32794
#define ID_LOADPROFILE                  32795
#define ID_MUDCLIENT_EXIT               32796
#define ID_MUDCLIENT_ABOUT              32797
#define ID_MUDCLIENT_HELP               32798
#define ID_NEWWORLD                     32799
#define ID_CHECK_UPDATES                32800
#define ID_MODE                         32801

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        225
#define _APS_NEXT_COMMAND_VALUE         32802
#define _APS_NEXT_CONTROL_VALUE         1149
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
